<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\..\bin\Debug</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\..\bin\Release</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="data\IndexedLineSet_Cases.wrl" />
    <EmbeddedResource Include="data\IndexedLineSet_Invalid_01.wrl" />
    <EmbeddedResource Include="data\IndexedLineSet_Invalid_02.wrl" />
    <EmbeddedResource Include="data\IndexedLineSet_Invalid_03.wrl" />
    <EmbeddedResource Include="data\IndexedLineSet_Invalid_04.wrl" />
    <EmbeddedResource Include="data\IndexedLineSet_Invalid_05.wrl" />
    <EmbeddedResource Include="data\IndexedLineSet_Invalid_06.wrl" />
    <EmbeddedResource Include="data\IndexedLineSet_Invalid_07.wrl" />
    <EmbeddedResource Include="data\IndexedLineSet_Invalid_08.wrl" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Aardvark.Data.Photometry\Aardvark.Data.Photometry.csproj" />
    <ProjectReference Include="..\..\Aardvark.Data.Vrml97\Aardvark.Data.Vrml97.csproj" />
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>