name: Linux

on: 
  push:
    paths-ignore:
    - 'README.md'
    - 'docs/'
  pull_request:
    paths-ignore:
    - 'README.md'
    - 'docs/'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Dotnet
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Add Paket credentials
      run: dotnet tool restore && dotnet paket config add-token https://nuget.pkg.github.com/aardvark-platform/index.json ${{ secrets.GITHUB_TOKEN }}          
    - name: Build
      run: sh ./build.sh
